blank_issues_enabled: false
contact_links:
  - name: 묻고 답하기
    url: https://github.com/commerce-api-naver/api-agency/discussions/categories/%EB%AC%BB%EA%B3%A0-%EB%8B%B5%ED%95%98%EA%B8%B0
    about: 커머스API 테스트 버전 사용 및 API대행사 운용 중 기술 문의 사항을 직접 게시하시어 답변을 받으실 수 있습니다.
