name: "동적 호출 허용량 설정 요청"
description: "커머스API 플랫폼 내 동적 호출 허용량 기능 사전 설정 요청"
title: "[설정요청] 동적 호출 허용량 설정 요청"
labels: []
assignees:
  - commerce-api-naver
body:
  - type: markdown
    attributes:
      value: |
        # 동적 호출 허용량 사전 설정 요청
        라이브 서비스 전환이 완료된 API대행사 소유의 대행사 애플리케이션 대상으로 동적 호출 허용량 기능 사전 설정을 요청합니다.
        설정 내용은 API대행사 이용자 규모에 따라 차등 적용됩니다.
  - type: markdown
    attributes:
      value: |
        ### API대행사 확인
        요청 대상 API대행사를 식별할 수 있는 검증용 API 호출건의 호출 정보를 입력합니다.
        - 제출하신 호출 정보로 대행사를 식별할 수 없는 경우 요청은 처리되지 않습니다.
        - 검증용 API 호출건은 요청일 기준 최근 1주일 이내 호출건으로 작성해주시기 바랍니다.
  - type: input
    id: agency-name
    attributes:
      label: 대행사명
      description: 최초 신청 시 등록 정보 기준
    validations:
      required: true
  - type: input
    id: agency-api-name
    attributes:
      label: 호출 API
      description: |
        검증용 API 호출 진행에 사용한 API 이름
        (예: "[상품] 채널 상품 조회" 또는 "GET /v2/products/channel-products/{channelProductNo}")
    validations:
      required: true
  - type: input
    id: agency-api-request
    attributes:
      label: 호출 일시
      description: 검증용 API 호출을 진행한 대략적인 날짜와 시간 (한국 표준시)
    validations:
      required: true
  - type: input
    id: agency-api-traceid
    attributes:
      label: Trace ID
      description: 검증용 API 호출건에 HTTP 응답 헤더(Response Header)로 제공된 'GNCP-GW-Trace-ID' 항목 값
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        ---
        ### 동적 호출 허용량 설정
        사전 설정 과정에서 게시된 [<공지사항: 동적 호출 허용량 설정 사전 적용>](https://github.com/commerce-api-naver/api-agency/discussions/12) 내용을 확인해주시기 바랍니다.
  - type: checkboxes
    attributes:
      label: 공지사항을 모두 확인하셨나요?
      options:
        - label: 네, 언급된 공지사항 내용을 모두 확인하고 이해하였습니다.
          required: true
  - type: textarea
    id: appendix
    attributes:
      label: 추가 입력 (선택)
      description: Markdown 서식 지원
      render: markdown
    validations:
      required: false
  - type: markdown
    attributes:
      value: |
        > [!IMPORTANT]
        > 요청 내용은 게시 즉시 다른 사용자에게 공개되며 되돌릴 수 없습니다.
        > 작성 내용 중 공개되어선 안되는 정보가 있는지 다시 확인하시기 바랍니다. (개인정보, 대외비 등)